[workspace]
members = ["crates/tessera-core", "src-tauri"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.89"
repository = "https://github.com/ManvithaP-hub/tessera"
authors = ["Manvitha Potluri"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
